apps/hub/urls.py
from django.urls import path,re_path
from .views import *

app_name="Hub"
urlpatterns = [
    re_path(r'^making_comment/(?P<slug>[\w\-]+)/$',Making_CommentsView.as_view(), name='making_comment'),
    path("giving_score/",Giving_Score_View, name='giving_score'),
    path("add_to_wish_list/",Add_To_Wish_List_View, name='add_to_wish_list'),
    path("wish_list/",Wish_List_View.as_view(), name='wish_list'),
]

apps/main/urls.py
from django.urls import path
from .views import * 
# from apps.main.views import * 

app_name="main"
urlpatterns = [
    path("",index,name="index"),
    path("set_slider",set_slider_view.as_view(),name="set_slider"),
]

apps/products/urls.py
from django.urls import path,re_path
from .views import *



app_name="products" 
urlpatterns = [
    path("cheapest_products/",fetch_cheapest_products_view,name="cheapest_products"),
    path("latest_products/",fetching_latest_products_view,name="latest_products"),
    path("popular_groups/",fetching_popular_groups_view,name="popular_groups"),
    re_path(r'^product_detail/(?P<slug>[\w\-]+)/$', fetching_product_detail_view.as_view(), name='product_detail'),
    # path("product_detail/<slug:slug>/",fetching_product_detail_view.as_view(),name="product_detail"),
    # path("related_products/<slug:slug>/",fetching_related_products_view,name="related_products"),
    path("all_groups/",feching_all_groups_view.as_view(),name="all_groups"),
    
    re_path(r'^products/(?P<slug>[\w\-]+)/$', feching_products_view.as_view(), name='products'),
    # path("products/<slug:slug>/",feching_products_view.as_view(),name="products"),
    path("all_groups_2/",fetching_all_groups_2_view,name="all_groups_2"),
    re_path(r'^all_brands/(?P<slug>[\w\-]+)/$', feching_all_brands_view, name='all_brands'),
    # path("all_brands/<slug:slug>/",feching_all_brands_view,name="all_brands"),
    re_path(r'^filters_for_features/(?P<slug>[\w\-]+)/$', fetching_filters_for_features_view, name='filters_for_features'),
    # path("filters_for_features/<slug:slug>/",fetching_filters_for_features_view,name="filters_for_features"),
    
    path("features_admin/",fetching_features_in_admin_view,name="features_admin"),
    
    path("search/",Search_Products_View.as_view(),name="search"),
    
    path("comparison_list/",Show_Comparison_List_View.as_view(),name="comparison_list"),
    path("comparison_table/",Comparison_Table_View,name="comparison_table"),
    path("status_of_comparison_list/",Status_Of_Comparison_List_View,name="status_of_comparison_list"),
    path("add_to_comparison_list/",Add_To_Comparison_List_VIEW,name="Add_to_comparison_list"),
    path("del_from_comparison_list/",Del_From_Comparison_List_VIEW,name="Del_from_comparison_list"),
]

apps/shop_cart/urls.py
from django.urls import path,re_path
from .views import *


app_name="Shopping_Cart"
urlpatterns = [
    path("shopping_cart/",Shopping_Cart_View.as_view(),name="shopping_cart"),
    path("show_shopping_cart/",show_shopping_cart_view,name="show_shopping_cart"),
    path("status_of_cart/",status_of_cart,name="status_of_cart"),
    path("add_to_cart/",add_to_cart,name="add_to_cart"),
    path("del_from_cart/",del_from_cart,name="del_from_cart"),
    path("update_cart/",update_cart,name="update_cart"),
    path("create_order/",Create_Order_View.as_view(),name="create_order"),
    # path("checkout/<int:order_id>/",Checkout_View.as_view(),name="checkout"),
    re_path(r'^checkout/(?P<order_id>[\w\-]+)/$', Checkout_View.as_view(), name='checkout'),
    re_path(r'^confirm_discount/(?P<order_id>[\w\-]+)/$', ConfirmDiscountView.as_view(), name='confirm_discount'),
]

online_shopping/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings 
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("apps.main.urls",namespace="main")),
    path('accounting/',include("apps.accounting.urls",namespace="accounting")),
    path("main_products/",include("apps.products.urls",namespace="products")),
    path("main_shopping_cart/",include("apps.shop_cart.urls",namespace="Shopping_Cart")),
    path("discount/",include("apps.discount.urls",namespace="Discount")),
    path("payments/",include("apps.payments.urls",namespace="Payments")),
    path("warehouse/",include("apps.warehouse.urls",namespace="Warehouse")),
    path("hub/",include("apps.hub.urls",namespace="Hub")),
    path("ckeditor",include("ckeditor_uploader.urls")),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


# admin.site.site_title = ""
admin.site.site_header="مدیریت پایگاه داده"
# admin.site.index_title=""

handler404 = "apps.main.views.handler404_view"

templates/partials/footer.html
<!-- site__footer -->
<footer class="site__footer">
    <div class="site-footer">
        <div class="container">
            <div class="site-footer__widgets">
                <div class="row">
                    <div class="col-12 col-md-6 col-lg-4">
                        <div class="site-footer__widget footer-contacts">
                            <h5 class="footer-contacts__title">تماس با ما</h5>

                            <ul class="footer-contacts__contacts">
                                <li><i class="footer-contacts__icon fa fa-map-marker" aria-hidden="true"></i><a href="https://neshan.org/maps/routing/car/destination/35.755345,51.328621/poi_hash/c10289188dfca2c1c050eac35a3ef59e/#c35.710-51.368-12z-0p" target="_blank">تهران - پونک بلوار عدل</a></li>
                                <li><i class="footer-contacts__icon fa fa-phone" aria-hidden="true"></i>
                                    <span class="ltr_text">021 - 444247..</span>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-6 col-md-3 col-lg-2">
                        <div class="site-footer__widget footer-links">
                            <h5 class="footer-links__title">اطلاعات</h5>
                            <ul class="footer-links__list">
                                <li class="footer-links__item">
                                    <a href="#" class="footer-links__link">درباره ما</a>
                                </li>
                                <li class="footer-links__item">
                                    <a href="#" class="footer-links__link">تماس با ما</a>
                                </li>
                                <li class="footer-links__item">
                                    <a href="#" class="footer-links__link">قوانین و مقررات</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-6 col-md-3 col-lg-2">
                        <div class="site-footer__widget footer-links">
                            <h5 class="footer-links__title">حساب کاربری</h5>
                            <ul class="footer-links__list">
                                <li class="footer-links__item">
                                    <a href="{% url "accounting:login_user" %}" class="footer-links__link">
                                        ورود
                                    </a>
                                </li>
                                <li class="footer-links__item">
                                    <a href="{% url "accounting:register_user" %}" class="footer-links__link">
                                        ثبت نام
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-12 col-md-12 col-lg-4">
                        <div class="site-footer__widget footer-newsletter">
                            <h5 class="footer-contacts__title">شبکه های</h5>
                            <div class="footer-newsletter__text footer-newsletter__text--social">ما را در شبکه های اجتماعی دنبال کنید</div>
                            <ul class="footer-newsletter__social-links">
                                <li
                                    class="footer-newsletter__social-link footer-newsletter__social-link--facebook">
                                    <a href="#" target="_blank"><i class="fab fa-facebook-f"></i></a>
                                </li>
                                <li
                                    class="footer-newsletter__social-link footer-newsletter__social-link--twitter">
                                    <a href="#" target="_blank"><i class="fab fa-twitter"></i></a>
                                </li>
                                <li
                                    class="footer-newsletter__social-link footer-newsletter__social-link--youtube">
                                    <a href="#" target="_blank"><i class="fab fa-youtube"></i></a>
                                </li>
                                <li
                                    class="footer-newsletter__social-link footer-newsletter__social-link--instagram">
                                    <a href="#" target="_blank"><i class="fab fa-instagram"></i></a>
                                </li>
                                <li class="footer-newsletter__social-link footer-newsletter__social-link--rss">
                                    <a href="#" target="_blank"><i class="fas fa-rss"></i></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="site-footer__bottom">
                <div class="site-footer__copyright">
                    کلیه حقوق و امتیازات این وبسایت متعلق است به <strong>سهیل دلیری</strong>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- site__footer / end -->

templates/partials/header.html
<!-- desktop site__header -->
<header class="site__header d-lg-block d-none">
    <div class="site-header">
        <!-- .topbar -->
        <div class="site-header__topbar topbar">
            <div class="topbar__container container">
                <div class="topbar__row">
                    {% comment %} <div class="topbar__item topbar__item--link"><a class="topbar-link" href="about-us.html">درباره ما</a></div>
                    <div class="topbar__item topbar__item--link"><a class="topbar-link" href="contact-us.html">تماس با ما</a></div> {% endcomment %}
                    <div class="topbar__spring"></div>
                    <div class="topbar__item">
                        <div class="topbar-dropdown">
                            {% if user.is_authenticated %}
                            <button class="topbar-dropdown__btn" type="button">
                                <i class="fa fa-user"></i>
                                <a href="{% url "accounting:dashboard" %}" class="topbar-link">{{ request.session.display_name }}</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                <a href="{% url "accounting:logout_user" %}" class="topbar-link">خروج</a>
                            </button>
                            {% else %}
                            <button class="topbar-dropdown__btn" type="button">
                                <a>{{ request.session.display_name }}</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                <a href="{% url "accounting:login_user" %}" class="topbar-link">ورود به حساب کاربری</a>&nbsp;&nbsp;<span>|</span>&nbsp;
                                <a href="{% url "accounting:register_user" %}" class="topbar-link">ثبت نام</a>
                            </button>
                            {% endif %}
                        </div>
                    </div>

                </div>
            </div>
        </div>

        <div class="site-header__middle container">
            <div class="site-header__logo">
                <a href="{% url "main:index" %}">
                    {% comment %} <img src="{{media_url}}images/logo.png" alt=""> {% endcomment %}
                </a>
            </div>
            <div class="site-header__search">
                <div class="search">
                    <form class="search__form" action="{% url "products:search" %}">
                        <input class="search__input" name="q" placeholder="جستجو در میان محصول"
                            aria-label="Site search" type="text" autocomplete="off">
                        <button class="search__button" type="submit">
                            <i class="fa fa-search"></i>
                        </button>
                        <div class="search__border"></div>
                    </form>
                </div>
            </div>
            <div class="site-header__phone">
                <div class="site-header__phone-title">پشتیبانی</div>
                <div class="site-header__phone-number"><span class="ltr_text">021 - 444247..</span></div>
            </div>
        </div>
        <!-- .topbar / end -->
        <div class="site-header__nav-panel">
            <div class="nav-panel">
                <div class="nav-panel__container container">
                    <div class="nav-panel__row">
                        <div class="nav-panel__logo">
                            <a href="{% url "main:index" %}">
                                <img src="{{media_url}}images/shopLogo.png" alt="shopLogo">
                            </a>
                        </div>
                        <!-- .nav-links -->
                        {% include "partials/navbar.html" %}
                        <!-- .nav-links / end -->
                        <div class="nav-panel__indicators">
                            <div class="indicator indicator--trigger--click">
                                <button type="button" class="indicator__button">
                                    <span class="indicator__area">
                                        {% comment %} <i class="fa fa-search"></i> {% endcomment %}
                                    </span>
                                </button>
                                <div class="indicator__dropdown">
                                    <div class="drop-search">
                                        <form action="{% url "products:search" %}" class="drop-search__form">
                                            <input class="drop-search__input" name="q" 
                                                placeholder="جستجو در میان محصولات"
                                                aria-label="Site search" type="text" autocomplete="off">
                                            <button class="drop-search__button drop-search__button--submit"
                                                type="submit">
                                                {% comment %} <i class="fa fa-search"></i> {% endcomment %}
                                            </button>
                                        </form>
                                    </div>
                                </div> 
                            </div>
                            <div id="comparison_icon" class="indicator">
                                <a href="{% url "products:comparison_list" %}" class="indicator__button">
                                    <span class="indicator__area">
                                        <i class="fa fa-random" aria-hidden="true" style="color:white;"></i>
                                        <span id="comparison_count" class="indicator__value">0</span>
                                    </span>
                                </a>
                            </div>

                            <div class="indicator">
                                <a href="{% url "Hub:wish_list" %}" class="indicator__button">
                                    <span class="indicator__area">
                                        <i class="fa fa-heart" style="color:white;"></i>
                                    </span>
                                </a>
                            </div>
                      
                            <div class="indicator">
                                <a href="{% url "Shopping_Cart:shopping_cart" %}" class="indicator__button">
                                    <span class="indicator__area">
                                        <i class="fa fa-shopping-cart"></i>
                                        <span class="indicator__value" id="indicator__value">0</span>
                                    </span>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- desktop site__header / end -->

templates/partials/navbar.html
<div class="nav-panel__nav-links nav-links">
    <ul class="nav-links__list">
        <li class="nav-links__item nav-links__item--with-submenu">
            <a href="{% url "main:index" %}">
                <span><i class="fa fa-home"></i>&nbsp; خانه</span>
            </a>
        </li>
        <li class="nav-links__item nav-links__item--with-submenu">
            <a href="#">
                <span>
                    دسته بندی کالاها
                    &nbsp;
                    <i class="fa fa-angle-down"></i>
                </span>
            </a>
            <div class="nav-links__megamenu nav-links__megamenu--size--nl">
                <!-- .megamenu -->
                <div class="megamenu">
                    <div class="row">
                        <div class="col-4">
                            <ul class="megamenu__links megamenu__links--level--0">
                                <li class="megamenu__item megamenu__item--with-submenu">
                                    <a href="">کالای دیجیتال</a>
                                    <ul
                                        class="megamenu__links megamenu__links--level--1">
                                        <li class="megamenu__item">
                                            <a href="product-list.html">موبایل</a>
                                            <ul>
                                                <li class="megamenu__links--level--2">
                                                    <a href="#">لوازم جانبی</a>
                                                </li>
                                                <li class="megamenu__links--level--2">
                                                    <a href="#">گوشی</a>
                                                </li>
                                            </ul>
                                        </li>
                                        <li class="megamenu__item">
                                            <a href="#">دوربین</a>
                                        </li>
                                        <li class="megamenu__item">
                                            <a href="#">لپ تاپ</a>
                                        </li>
                                        <li class="megamenu__item">
                                            <a href="#">سخت افزار کامپیوتر</a>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                        <div class="col-4">
                            <ul class="megamenu__links megamenu__links--level--0">
                                <li class="megamenu__item megamenu__item--with-submenu">
                                    <a href="">مد و پوشاک</a>
                                    <ul
                                        class="megamenu__links megamenu__links--level--1">
                                        <li class="megamenu__item">
                                            <a href="#">مردانه</a>
                                            <ul>
                                                <li class="megamenu__links--level--2">
                                                    <a href="#">پیراهن</a>
                                                </li>
                                                <li class="megamenu__links--level--2">
                                                    <a href="#">شلوار</a>
                                                </li>
                                                <li class="megamenu__links--level--2">
                                                    <a href="#">کفش</a>
                                                </li>
                                            </ul>
                                        </li>
                                        <li class="megamenu__item">
                                            <a href="#">زنانه</a>
                                            <ul>
                                                <li class="megamenu__links--level--2">
                                                    <a href="#">پیراهن</a>
                                                </li>
                                                <li class="megamenu__links--level--2">
                                                    <a href="#">شلوار</a>
                                                </li>
                                                <li class="megamenu__links--level--2">
                                                    <a href="#">کفش</a>
                                                </li>
                                            </ul>
                                        </li>
                                        <li class="megamenu__item">
                                            <a href="#">بچه گانه</a>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                        <div class="col-4">
                            <ul class="megamenu__links megamenu__links--level--0">
                                <li class="megamenu__item megamenu__item--with-submenu">
                                    <a href="">مواد غذایی</a>
                                    <ul
                                        class="megamenu__links megamenu__links--level--1">
                                        <li class="megamenu__item">
                                            <a href="#">کالای اساسی و خواربار</a>
                                            <ul>
                                                <li class="megamenu__links--level--2">
                                                    <a href="#">برنج</a>
                                                </li>
                                                <li class="megamenu__links--level--2">
                                                    <a href="#">قند</a>
                                                </li>
                                                <li class="megamenu__links--level--2">
                                                    <a href="#">سایر</a>
                                                </li>
                                            </ul>
                                        </li>
                                        <li class="megamenu__item">
                                            <a href="#">نوشیدنی</a>
                                            <ul>
                                                <li class="megamenu__links--level--2">
                                                    <a href="#">چای</a>
                                                </li>
                                                <li class="megamenu__links--level--2">
                                                    <a href="#">دمنوش</a>
                                                </li>
                                            </ul>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </div>

                    </div>
                </div>
                <!-- .megamenu / end -->
                {% comment %} <!-- .menu -->
            </div>
        </li>

        <li class="nav-links__item nav-links__item--with-submenu">
            <a href="#">
                <span>
                    حساب کاربری&nbsp;<i class="fa fa-angle-down"></i>
                </span>
            </a>
            <div class="nav-links__menu">
                {% if user.is_authenticated %}
                <ul class="menu menu--layout--classic">
                    <li><a href="{% url "accounting:logout_user" %}">خروج</a></li>
                </ul>
                {% else %}
                <ul class="menu menu--layout--classic">
                    <li><a href="{% url "accounting:login_user" %}">ورود</a></li>
                    <li><a href="{% url "accounting:register_user" %}">ثبت نام</a></li>
                </ul>
                {% endif %} {% endcomment %}
                <!-- .menu / end -->
            </div>
        </li>
        {% comment %} <li class="nav-links__item nav-links__item--with-submenu">
            <a href="#">
                <span><i class="fa fa-newspaper"></i>&nbsp; بلاگ</span>
            </a>
        </li> {% endcomment %}
    </ul>
</div>

templates/partials/warning_mesaages.html
<div class="container">
    {% if messages %}
        {% for message in messages %}
            <h1 class="alert alert-{{ message.tags }}">{{ message }}</h1>
        {% endfor %}
    {% endif %}
</div>