apps/accounting/urls.py
from django.urls import path
from .views import *


app_name="accounting"
urlpatterns = [
    path("register_user/",RegisterUserView.as_view(),name="register_user"),
    path("verufy_cell_num/",VerifyingCellNumberView.as_view(),name="verufy_cell_num"),
    path("login_user/",LoginUserView.as_view(),name="login_user"),
    path("logout_user/",LogoutUserView.as_view(),name="logout_user"),
    path("changing_pass/",ChangingPasswordView.as_view(),name="changing_pass"),
    path("remember_pass/",RememberPasswordView.as_view(),name="remember_pass"),
    path("dashboard/",DashboardView.as_view(),name="dashboard"),
    path("update_profile/",Update_Profile_View.as_view(),name="update_profile"),
    path("fetch_orders/",fetch_orders,name="fetch_orders"),
    path("fetch_payments/",fetch_payments,name="fetch_payments"),
]

apps/hub/urls.py
from django.urls import path,re_path
from .views import *

app_name="Hub"
urlpatterns = [
    re_path(r'^making_comment/(?P<slug>[\w\-]+)/$',Making_CommentsView.as_view(), name='making_comment'),
    path("giving_score/",Giving_Score_View, name='giving_score'),
    path("add_to_wish_list/",Add_To_Wish_List_View, name='add_to_wish_list'),
    path("wish_list/",Wish_List_View.as_view(), name='wish_list'),
]

apps/main/urls.py
from django.urls import path
from .views import * 
# from apps.main.views import * 

app_name="main"
urlpatterns = [
    path("",index,name="index"),
    path("set_slider",set_slider_view.as_view(),name="set_slider"),
]

apps/products/urls.py
from django.urls import path,re_path
from .views import *



app_name="products" 
urlpatterns = [
    path("cheapest_products/",fetch_cheapest_products_view,name="cheapest_products"),
    path("latest_products/",fetching_latest_products_view,name="latest_products"),
    path("popular_groups/",fetching_popular_groups_view,name="popular_groups"),
    re_path(r'^product_detail/(?P<slug>[\w\-]+)/$', fetching_product_detail_view.as_view(), name='product_detail'),
    # path("product_detail/<slug:slug>/",fetching_product_detail_view.as_view(),name="product_detail"),
    # path("related_products/<slug:slug>/",fetching_related_products_view,name="related_products"),
    path("all_groups/",feching_all_groups_view.as_view(),name="all_groups"),
    
    re_path(r'^products/(?P<slug>[\w\-]+)/$', feching_products_view.as_view(), name='products'),
    # path("products/<slug:slug>/",feching_products_view.as_view(),name="products"),
    path("all_groups_2/",fetching_all_groups_2_view,name="all_groups_2"),
    re_path(r'^all_brands/(?P<slug>[\w\-]+)/$', feching_all_brands_view, name='all_brands'),
    # path("all_brands/<slug:slug>/",feching_all_brands_view,name="all_brands"),
    re_path(r'^filters_for_features/(?P<slug>[\w\-]+)/$', fetching_filters_for_features_view, name='filters_for_features'),
    # path("filters_for_features/<slug:slug>/",fetching_filters_for_features_view,name="filters_for_features"),
    
    path("features_admin/",fetching_features_in_admin_view,name="features_admin"),
    
    path("search/",Search_Products_View.as_view(),name="search"),
    
    path("comparison_list/",Show_Comparison_List_View.as_view(),name="comparison_list"),
    path("comparison_table/",Comparison_Table_View,name="comparison_table"),
    path("status_of_comparison_list/",Status_Of_Comparison_List_View,name="status_of_comparison_list"),
    path("add_to_comparison_list/",Add_To_Comparison_List_VIEW,name="Add_to_comparison_list"),
    path("del_from_comparison_list/",Del_From_Comparison_List_VIEW,name="Del_from_comparison_list"),
]

online_shopping/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings 
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("apps.main.urls",namespace="main")),
    path('accounting/',include("apps.accounting.urls",namespace="accounting")),
    path("main_products/",include("apps.products.urls",namespace="products")),
    path("main_shopping_cart/",include("apps.shop_cart.urls",namespace="Shopping_Cart")),
    path("discount/",include("apps.discount.urls",namespace="Discount")),
    path("payments/",include("apps.payments.urls",namespace="Payments")),
    path("warehouse/",include("apps.warehouse.urls",namespace="Warehouse")),
    path("hub/",include("apps.hub.urls",namespace="Hub")),
    path("ckeditor",include("ckeditor_uploader.urls")),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


# admin.site.site_title = ""
admin.site.site_header="مدیریت پایگاه داده"
# admin.site.index_title=""

handler404 = "apps.main.views.handler404_view"

apps/hub/models.py
from django.db import models
from django.core.validators import MinValueValidator,MaxValueValidator
from apps.accounting.models import CustomUser
from apps.products.models import Products


#============================================================================
class Comments(models.Model):
    product = models.ForeignKey(Products,on_delete=models.CASCADE,related_name="Commetnt_Product",verbose_name="کالا")
    user = models.ForeignKey(CustomUser,on_delete=models.CASCADE,related_name="Comment_User",verbose_name="کاربر")
    admin = models.ForeignKey(CustomUser,on_delete=models.CASCADE,related_name="Comment_Admin",verbose_name="ادمین",blank=True,null=True)
    comment = models.TextField(verbose_name="نظر")
    comment_parent = models.ForeignKey("Comments",on_delete=models.CASCADE,related_name="Comment_Parent",blank=True,null=True)
    created_at = models.DateTimeField(auto_now_add=True,verbose_name="تارخ ثبت")
    is_active = models.BooleanField(default=False,verbose_name="وضعیت فعال بودن")
    
    def __str__(self):
        return f"{self.product} {self.user}"
    
    class Meta:
        verbose_name = "نظر"
        verbose_name_plural = "نظرات"
        
        
#============================================================================
class Scores(models.Model):
    product = models.ForeignKey(Products,on_delete=models.CASCADE,related_name="Score_Product",verbose_name="کالا")
    user = models.ForeignKey(CustomUser,on_delete=models.CASCADE,related_name="Score_User",verbose_name="کاربر")
    created_at = models.DateTimeField(auto_now_add=True,verbose_name="تارخ ثبت")
    score = models.PositiveSmallIntegerField(validators=[MinValueValidator(0),MaxValueValidator(5)],verbose_name="امتیاز")

    def __str__(self):
        return f"{self.product} {self.user}"
    
    class Meta:
        verbose_name = "امتیاز"
        verbose_name_plural = "امتیازات"


#============================================================================
class UserWishlist(models.Model):
    product = models.ForeignKey(Products,on_delete=models.CASCADE,related_name="Wishlist_Product",verbose_name="کالا")
    user = models.ForeignKey(CustomUser,on_delete=models.CASCADE,related_name="Wishlist_User",verbose_name="کاربر")
    created_at = models.DateTimeField(auto_now_add=True,verbose_name="تارخ ثبت")

    def __str__(self):
        return f"{self.product} {self.user}"
    
    class Meta:
        verbose_name = "علاقه مندی"
        verbose_name_plural = "علاقه مندی ها"

#============================================================================

apps/hub/forms.py
from django import forms 


class CommentForm(forms.Form):
    product_id = forms.CharField(widget=forms.HiddenInput(),required=False)
    comment_id = forms.CharField(widget=forms.HiddenInput(),required=False)
    comment = forms.CharField(
        label="",
        error_messages={"required":"این فیلد نمیتواند خالی باشد"},
        widget=forms.Textarea(attrs={"class":"form-control","placeholder":"نظر خود را وارد کنید","rows":"4"},
                              )
        )

apps/hub/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.views import View
from django.db.models import Q
from django.http import JsonResponse,HttpResponse
from django.contrib import messages
from .forms import *
from .models import *


#============================================================================
class Making_CommentsView(View):
    template_name = "hub/making_comment.html"
    
    def get(self,request,*args,**kwargs):
        product_Id = request.GET.get("product_Id")    
        comment_Id = request.GET.get("comment_Id")
        slug = kwargs["slug"]
        
        initial_values = {
            "product_id" : product_Id,
            "comment_id" : comment_Id,
        }    
        form = CommentForm(initial=initial_values)
        
        context = {
            "form":form,
            "slug":slug,
        }
        
        return render(request,self.template_name,context)
        
        
    def post(self,request,*args,**kwargs):
        slug = kwargs.get("slug")
        product = get_object_or_404(Products,slug=slug)                   
        parent = None  
        
        form = CommentForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            comment_id = data["comment_id"]
            if comment_id:
                parent = Comments.objects.get(id=comment_id)
                 
            Comments.objects.create(
                product = product,
                user = request.user,
                comment = data["comment"],
                comment_parent = parent,
            )
    
            messages.success(request,"نظر شما ثبت شد")
            return redirect("products:product_detail",product.slug)
        
        messages.error(request,"خطا در ارسال نظر","danger")
        return redirect("products:product_detail",product.slug)
    
    
#============================================================================
def Giving_Score_View(request):
    product_Id = request.GET.get("product_Id")
    score = request.GET.get("score")
    product = Products.objects.get(id=product_Id)
    
    Scores.objects.create(
        product = product,
        user = request.user,
        score = score, 
    )
    
    response_data = {
        'success': True,
        'message': 'امتیاز شما ثبت شد'
    }

    messages.success(request,"امتیاز شما ثبت شد","success")
    return JsonResponse(response_data)
    

#============================================================================
def Add_To_Wish_List_View(request):
    product_Id = request.GET.get("product_Id")
    product = Products.objects.get(id=product_Id)
    client = request.user
    wish_list = UserWishlist.objects.filter(Q(user_id=client.id) & Q(product_id=product_Id)).exists()
    
    response_data = {
        "success": True,
        "message_1": "این کالا به لیست علاقه مندی های شما اضافه شد",
        "message_2": "این کالا لیست علاقه مندی های شما وجود داشت",
    }
    
    if not wish_list:
        UserWishlist.objects.create(
            product = product,
            user = client
        )
        
        messages.success(request,"این کالا به لیست علاقه مندی های شما اضافه شد","success")
        return JsonResponse(response_data)
    
    messages.success(request,"این کالا لیست علاقه مندی های شما وجود داشت","success")
    return JsonResponse(response_data)
    

#============================================================================
class Wish_List_View(View):
    template_name = "hub/wish_list.html"
    
    def get(self,request,*args,**kwargs):
        user_wish_list = UserWishlist.objects.filter(Q(user_id=request.user.id))
        context = {
            "user_wish_list":user_wish_list,
        }
        return render(request,self.template_name,context)
    
    
#============================================================================
# def Confirm_Comments_View(self, request):

#     comments = Comments.objects.all()
#     admin_user = CustomUser.objects.get(is_admin=True)
    
#     for comment in comments:
#         if comment.is_active:
#             Comments.objects.create(
#                 admin = admin_user
#             )


#============================================================================

templates/hub/giving_score.html
<h6 style="margin-top:20px;">میانگین امتیاز : <span>{{product.cal_avg_score}}</span></h6>

{% if user.is_authenticated %}
        {% if product.fetch_score > 0 %}
            <div style="margin-top:20px;">
                {% with ''|center:5 as range %}
                    {% for i in range %}
                        {% if forloop.counter <= product.fetch_score %}
                            <span id="star_{{ forloop.counter }}" class="fa fa-star checked"></span>
                        {% else %}
                            <span id="star_{{ forloop.counter }}" class="fa fa-star"></span>
                        {% endif %}
                    {% endfor %}
                {% endwith %}
            </div>
        {% else %}
            <div style="margin-top:20px;">
                <span id="star_1" class="fa fa-star cursor_pointer" onclick="giving_score(1,{{product.id}})"></span>
                <span id="star_2" class="fa fa-star cursor_pointer" onclick="giving_score(2,{{product.id}})"></span>
                <span id="star_3" class="fa fa-star cursor_pointer" onclick="giving_score(3,{{product.id}})"></span>
                <span id="star_4" class="fa fa-star cursor_pointer" onclick="giving_score(4,{{product.id}})"></span>
                <span id="star_5" class="fa fa-star cursor_pointer" onclick="giving_score(5,{{product.id}})"></span>
            </div>
        {% endif %} 
{% else %}
    {% comment %} <h5>
        <a href="{% url "accounting:login_user" %}?next=/products/{{products.slug}}/">ورود</a>
        یا
        <a href="{% url "accounting:register_user" %}?next=/products/{{products.slug}}/">ثبت نام</a>
        کنید
    </h5> {% endcomment %}
{% endif %}

templates/hub/making_comment.html
<h3 class="reviews-view__header">دیدگاه خود را بنویسید</h3>
<div class="row">
    <div class="col-12 col-lg-9 col-xl-8">
        <form action="{% url "Hub:making_comment" slug=slug %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="review-text">دیدگاه شما</label>
                {{form}}
            </div>
            <div class="form-group mb-0">
                <button type="submit" class="btn btn-primary btn-lg">ارسال</button>
            </div>
        </form>
    </div>
</div>

templates/hub/reading_comments.html
<h3 class="reviews-view__header">دیدگاه های مشتریان</h3>
<div class="reviews-list">
    <ol class="reviews-list__content">
        {% for comment in product.Commetnt_Product.all %}
            {% if comment.is_active %}
                {% if comment.comment_parent == None %}
                    <li class="reviews-list__item" style="display:flex; justify-content:space-between;">
                        <div class="review">
                            <div class="review__avatar">
                                <img src="{{media_url}}images/avatars/avatar-1.jpg" alt=""></div>
                            <div class="review__content">
                                <div class="review__author">{{comment.user.first_name}} {{comment.user.last_name}}</div>
                                <div class="review__text">{{comment.comment}}</div>
                                <div class="review__date">{{comment.logged_date}}</div>
                            </div>
                        </div>
                        <div>
                            {% if user.is_authenticated %}

                            <div>
                                <a class="btn btn-info" id="btn_{{comment.id}}" onclick="ShowComments({{product.id}},{{comment.id}},'{{product.slug}}')">پاسخ</a>
                            </div>
                            <div id="comment_form_{{comment.id}}"> <div>
                            {% endif %}
                        </div>
                    </li>
                    {% for item in comment.Comment_Parent.all  %}
                        {% if comment.is_active %}
                            <li class="reviews-list__item" style="background-color:beige; width:95%; margin:10px 5%;">
                                <div class="review">
                                    <div class="review__avatar">
                                        <img src="{{media_url}}images/avatars/avatar-4.jpg" alt=""></div>
                                    <div class="review__content">
                                        <div class="review__author">{{item.user.first_name}} {{item.user.last_name}}</div>
                                        <div class="review__text">{{item.comment}}</div>
                                        <div class="review__date">{{item.logged_date}}</div>
                                    </div>
                                </div>
                            </li>
                        {% endif %}
                    {% endfor %}

                {% else %}

                {% endif %} 
            {% endif %}
        {% endfor %}
    </ol>
</div>

templates/hub/wish_list.html
{% extends "main_template.html" %}
{% load render_partial %}
{% load humanize %}

{% block title %}لیست علاقه مندی ها{% endblock %}

{% block content %}
<div class="site__body">
	<div class="page-header">
		<div class="page-header__container container">
			<div class="page-header__breadcrumb">
				<nav aria-label="breadcrumb">
					<ol class="breadcrumb">
						<li class="breadcrumb-item">
                            <a href="{% url "main:index" %}">خانه</a>/
                        </li>
						<li class="breadcrumb-item">
                            <a href="{% url "Hub:wish_list" %}">علاقه مندی ها</a>
                        </li>
					</ol>
				</nav>
			</div>
			<div class="page-header__title">
				<h1>لیست علاقه مندی ها</h1></div>
		</div>
	</div>
	<div class="block">
		<div class="container">
			<table class="wishlist">
				<thead class="wishlist__head">
					<tr class="wishlist__row">
						<th class="wishlist__column wishlist__column--image">تصویر</th>
						<th class="wishlist__column wishlist__column--product">محصول</th>
						<th class="wishlist__column wishlist__column--stock">وضعیت انبار</th>
						<th class="wishlist__column wishlist__column--price">قیمت</th>
						<th class="wishlist__column wishlist__column--tocart"></th>
						<th class="wishlist__column wishlist__column--remove"></th>
					</tr>
				</thead>
				<tbody class="wishlist__body">
					{% for item in user_wish_list %}

						<tr class="wishlist__row">
							<td class="wishlist__column wishlist__column--image">
								<a href=""><img src="{{media_url}}{{item.product.image}}" alt=""></a>
							</td>
							<td class="wishlist__column wishlist__column--product">
								<a href="{% url "products:product_detail" slug=item.product.slug %}" class="wishlist__product-name">
									{{item.product.title}}
								</a>
							</td>
							<td class="wishlist__column wishlist__column--stock">
								{% if item.product.fetch_count_of_product > 0 %}
									<div class="badge badge-success">موجود در انبار</div>
								{% else %}
									<div class="badge badge-danger">موجود نمیباشد</div>
								{% endif %}
							</td>
							<td class="wishlist__column wishlist__column--price">{{item.product.price|intcomma:False}} تومان</td>
							<td class="wishlist__column wishlist__column--tocart">
								{% if item.product.fetch_count_of_product > 0 %}
									<button type="button" class="btn btn-primary btn-sm" onclick="add_to_cart({{product.id}},1)">افزودن به سبد</button>
								{% else %}
									<button type="button" class="btn btn-info disable btn-sm">افزودن به سبد</button>
								{% endif %}
							</td>
							<td class="wishlist__column wishlist__column--remove">
								<button type="button" class="btn btn-light btn-sm btn-svg-icon">
									<svg width="12px" height="12px">
										<use xlink:href="{{media_url}}images/sprite.svg#cross-12"></use>
									</svg>
								</button>
							</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
</div>
{% endblock content %}