apps/accounting/urls.py
from django.urls import path
from .views import *


app_name="accounting"
urlpatterns = [
    path("register_user/",RegisterUserView.as_view(),name="register_user"),
    path("verufy_cell_num/",VerifyingCellNumberView.as_view(),name="verufy_cell_num"),
    path("login_user/",LoginUserView.as_view(),name="login_user"),
    path("logout_user/",LogoutUserView.as_view(),name="logout_user"),
    path("changing_pass/",ChangingPasswordView.as_view(),name="changing_pass"),
    path("remember_pass/",RememberPasswordView.as_view(),name="remember_pass"),
    path("dashboard/",DashboardView.as_view(),name="dashboard"),
    path("update_profile/",Update_Profile_View.as_view(),name="update_profile"),
    path("fetch_orders/",fetch_orders,name="fetch_orders"),
    path("fetch_payments/",fetch_payments,name="fetch_payments"),
]

apps/main/urls.py
from django.urls import path
from .views import * 
# from apps.main.views import * 

app_name="main"
urlpatterns = [
    path("",index,name="index"),
    path("set_slider",set_slider_view.as_view(),name="set_slider"),
]

online_shopping/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings 
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("apps.main.urls",namespace="main")),
    path('accounting/',include("apps.accounting.urls",namespace="accounting")),
    path("main_products/",include("apps.products.urls",namespace="products")),
    path("main_shopping_cart/",include("apps.shop_cart.urls",namespace="Shopping_Cart")),
    path("discount/",include("apps.discount.urls",namespace="Discount")),
    path("payments/",include("apps.payments.urls",namespace="Payments")),
    path("warehouse/",include("apps.warehouse.urls",namespace="Warehouse")),
    path("hub/",include("apps.hub.urls",namespace="Hub")),
    path("ckeditor",include("ckeditor_uploader.urls")),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


# admin.site.site_title = ""
admin.site.site_header="مدیریت پایگاه داده"
# admin.site.index_title=""

handler404 = "apps.main.views.handler404_view"

templates/main_template.html
{% load static %}
<!DOCTYPE html>
<html lang="fa" dir="rtl">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <meta name="description" content="the content of this web site is experimental">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="format-detection" content="telephone=no">
        <meta name="keyword" content="HTML,Experimental">
        <meta name="author" content="Soheil Daliri">
        <meta name="robots" content="follow,index">
        <title>فروشگاه آنلاین | {% block title %} {% endblock %}</title>
        <link rel="icon" href="{{media_url}}images/django-favicon.png" sizes="64x64" type="image/png">
        <!-- css -->
        <link rel="stylesheet" href="{% static "vendor/bootstrap-4.5.3/css/bootstrap.min.css" %}">
        <link rel="stylesheet" href="{% static "vendor/owl-carousel-2.3.4/assets/owl.carousel.min.css" %}">
        <link rel="stylesheet" href="{% static "css/style.css" %}">
        <link rel="stylesheet" href="{% static "css/custom.css" %}">
        <!-- js -->
        <script src="{% static "vendor/jquery-3.3.1/jquery.min.js" %}"></script>
        <script src="{% static "vendor/bootstrap-4.5.3/js/bootstrap.bundle.min.js" %}"></script>
        <script src="{% static "vendor/owl-carousel-2.3.4/owl.carousel.min.js" %}"></script>
        <script src="{% static "js/main.js" %}"></script>
        {% comment %} <script src="{% static "js/countdown.js" %}"></script> {% endcomment %}
        <script src="{% static "js/filters.js" %}"></script>
        <script src="{% static "js/scripts.js" %}"></script>
        {% comment %} <script src="{% static "js/checked_checkbox.js" %}"></script> {% endcomment %}
        <!-- font - fontawesome -->
        <link rel="stylesheet" href="{% static "vendor/fontawesome-5.6.3/css/all.min.css" %}">
    </head>
    <body>

        {% include "partials/header.html" %}

        {% include "partials/warning_mesaages.html" %}

        
        {% block content %}
        
        {% endblock %}
        
        
        {% include "partials/footer.html" %}
    </body>
</html>

templates/user_template.html
{% load static %}
<!DOCTYPE html>
<html lang="fa" dir="rtl">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <meta name="description" content="the content of this web site is experimental">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="format-detection" content="telephone=no">
        <meta name="keyword" content="HTML,Experimental">
        <meta name="author" content="Soheil Daliri">
        <meta name="robots" content="follow,index">
        <title>فروشگاه آنلاین | {% block title %} {% endblock %}</title>
        <link rel="icon" href="{{media_url}}images/django-favicon.png" sizes="64x64" type="image/png">
        <!-- css -->
        <link rel="stylesheet" href="{% static "vendor/bootstrap-4.5.3/css/bootstrap.min.css" %}">
        <link rel="stylesheet" href="{% static "vendor/owl-carousel-2.3.4/assets/owl.carousel.min.css" %}">
        <link rel="stylesheet" href="{% static "css/style.css" %}">
        <link rel="stylesheet" href="{% static "css/custom.css" %}">
        <!-- js -->
        <script src="{% static "vendor/jquery-3.3.1/jquery.min.js" %}"></script>
        <script src="{% static "vendor/bootstrap-4.5.3/js/bootstrap.bundle.min.js" %}"></script>
        <script src="{% static "vendor/owl-carousel-2.3.4/owl.carousel.min.js" %}"></script>
        <script src="{% static "js/main.js" %}"></script>
        {% comment %} <script src="{% static "js/countdown.js" %}"></script> {% endcomment %}
        <script src="{% static "js/filters.js" %}"></script>
        <script src="{% static "js/scripts.js" %}"></script>
        {% comment %} <script src="{% static "js/checked_checkbox.js" %}"></script> {% endcomment %}
        <!-- font - fontawesome -->
        <link rel="stylesheet" href="{% static "vendor/fontawesome-5.6.3/css/all.min.css" %}">
    </head>
    <body>

        {% include "partials/header.html" %}

        {% include "partials/warning_mesaages.html" %}

        <div class="site__body">
            <div class="page-header">
                <div class="page-header__container container">
                    <div class="page-header__breadcrumb">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item">
                                    <a href="{% url "main:index" %}">خانه</a>/
                                </li>
                                <li class="breadcrumb-item">
                                    <a href="{% url "accounting:dashboard" %}">داشبورد</a>
                                </li>
                            </ol>
                        </nav>
                    </div>
                    <div class="page-header__title">
                        <h1>حساب کاربری</h1></div>
                </div>
            </div>
            <div class="block">
                <div class="container">
                    <div class="row">
                        <div class="col-12 col-lg-3 d-flex">
                            <div class="account-nav flex-grow-1">
                                <h4 class="account-nav__title">ناوبری</h4>
                                <ul>
                                    <li class="account-nav__item account-nav__item--active"><a href="{% url "accounting:dashboard" %}">داشبورد</a></li>
                                    <li class="account-nav__item"><a href="{% url "accounting:update_profile" %}">ویرایش پروفایل</a></li>
                                    <li class="account-nav__item"><a href="{% url "accounting:changing_pass" %}">تغییر رمز عبور</a></li>
                                    <li class="account-nav__item"><a href="{% url "accounting:fetch_payments" %}">سابقه خرید</a></li>
                                    <li class="account-nav__item"><a href="{% url "accounting:logout_user" %}">خروج</a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-12 col-lg-9 mt-4 mt-lg-0">
                            {% block content %}{% endblock %}
                        </div>
                    </div>
                </div>
            </div>
        </div>

        {% include "partials/footer.html" %}
    </body>
</html>